package com.insieme.common.domain.dto;

import com.google.gson.annotations.SerializedName;

/**
 * Simple track POJO structured to be serialized by JOOQ and mapped to the appropriate fields.
 * I chose to override the DTO generated by JOOQ although I kept it in the core database package for reference.
 */
public class TrackEntity extends RestEntity{

	public static final String TRACK_ID = "track-id";
	public static final String ARTIST_ID = "artist-id";
	public static final String GENRE = "genre";
	public static final String DOWNLOAD_COUNT = "download-count";
	public static final String DESCRIPTION = "description";
	public static final String NAME = "name";
	
	@SerializedName(TRACK_ID)
	private final String trackId;
	
	@SerializedName(ARTIST_ID)
	private final String artistId;
	
	@SerializedName(GENRE)
	private final String genre;
	
	@SerializedName(DOWNLOAD_COUNT)
	private final int downloadCount;
	
	@SerializedName(DESCRIPTION)
	private final String description;
	
	@SerializedName(NAME)
	private final String name;

	public TrackEntity(final String TRACK_ID, final String ARTIST_ID,
			final String GENRE, final int DOWNLOAD_COUNT,
			final String DESCRIPTION, final String TRACK_NAME) {
		this.trackId = TRACK_ID;
		this.artistId = ARTIST_ID;
		this.genre = GENRE;
		this.downloadCount = DOWNLOAD_COUNT;
		this.description = DESCRIPTION;
		this.name = TRACK_NAME;
	}

	/**
	 * @return the trackId
	 */
	public String getTrackId() {
		return trackId;
	}

	/**
	 * @return the artistId
	 */
	public String getArtistId() {
		return artistId;
	}

	/**
	 * @return the genre
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * @return the downloadCount
	 */
	public int getDownloadCount() {
		return downloadCount;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
}
