/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.tables.records;

import java.util.List;

import org.jooq.impl.UpdatableRecordImpl;

import com.insieme.common.database.tables.Artists;
import com.insieme.common.database.tables.Users;

/**
 * This class is generated by jOOQ.
 *
 * Table to keep track of basic user info.
 */
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

	private static final long serialVersionUID = -110422469;

	/**
	 * The table column <code>insieme.users.USER_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setUserId(String value) {
		setValue(Users.USERS.USER_ID, value);
	}

	/**
	 * The table column <code>insieme.users.USER_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public String getUserId() {
		return getValue(Users.USERS.USER_ID);
	}

	/**
	 * The table column <code>insieme.users.USER_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public List<ArtistsRecord> fetchArtistsList() {
		return create()
			.selectFrom(Artists.ARTISTS)
			.where(Artists.ARTISTS.ARTIST_ID.equal(getValue(Users.USERS.USER_ID)))
			.fetch();
	}

	/**
	 * User's first name
	 */
	public void setFirstName(String value) {
		setValue(Users.USERS.FIRST_NAME, value);
	}

	/**
	 * User's first name
	 */
	public String getFirstName() {
		return getValue(Users.USERS.FIRST_NAME);
	}

	/**
	 * User's last name
	 */
	public void setLastName(String value) {
		setValue(Users.USERS.LAST_NAME, value);
	}

	/**
	 * User's last name
	 */
	public String getLastName() {
		return getValue(Users.USERS.LAST_NAME);
	}

	/**
	 * User's encrypted password
	 */
	public void setUserPassword(String value) {
		setValue(Users.USERS.USER_PASSWORD, value);
	}

	/**
	 * User's encrypted password
	 */
	public String getUserPassword() {
		return getValue(Users.USERS.USER_PASSWORD);
	}

	/**
	 * User's email address
	 */
	public void setUserEmail(String value) {
		setValue(Users.USERS.USER_EMAIL, value);
	}

	/**
	 * User's email address
	 */
	public String getUserEmail() {
		return getValue(Users.USERS.USER_EMAIL);
	}

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}
}
