/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database;

import java.util.Arrays;
import java.util.List;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.insieme.common.database.tables.Artists;
import com.insieme.common.database.tables.Tracks;
import com.insieme.common.database.tables.Users;

/**
 * Insieme class for JOOQ.
 */
public class Insieme extends SchemaImpl {

	private static final long serialVersionUID = -71488107;

	/**
	 * The singleton instance of insieme
	 */
	public static final Insieme INSIEME = new Insieme();

	/**
	 * No further instances allowed
	 */
	private Insieme() {
		super("insieme");
	}

	@Override
	public final List<Table<?>> getTables() {
		return Arrays.<Table<?>>asList(
			Artists.ARTISTS,
			Tracks.TRACKS,
			Users.USERS);
	}
}
