/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database;

import com.insieme.common.database.tables.Artists;
import com.insieme.common.database.tables.Tracks;
import com.insieme.common.database.tables.Users;


/**
 * JOOQ class to keep track of tables in the database.
 */
public final class Tables {

	/**
	 * The table insieme.artists
	 */
	public static final Artists ARTISTS = Artists.ARTISTS;

	/**
	 * The table insieme.tracks
	 */
	public static final Tracks TRACKS = Tracks.TRACKS;

	/**
	 * Table to keep track of basic user info.
	 */
	public static final Users USERS = Users.USERS;

	/**
	 * No instances
	 */
	private Tables() {}
}
