/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.tables;

import java.util.Arrays;
import java.util.List;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.UpdatableTableImpl;

import com.insieme.common.database.Insieme;
import com.insieme.common.database.Keys;
import com.insieme.common.database.tables.records.UsersRecord;


/**
 * User table generated by JOOQ.
 */
public class Users extends UpdatableTableImpl<UsersRecord> {

	private static final long serialVersionUID = 1810340672;

	/**
	 * The singleton instance of insieme.users
	 */
	public static final Users USERS = new Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UsersRecord> getRecordType() {
		return UsersRecord.class;
	}

	/**
	 * The table column <code>insieme.users.USER_ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final TableField<UsersRecord, String> USER_ID = createField("USER_ID", SQLDataType.VARCHAR, this);

	/**
	 * User's first name
	 */
	public final TableField<UsersRecord, String> FIRST_NAME = createField("FIRST_NAME", SQLDataType.VARCHAR, this);

	/**
	 * User's last name
	 */
	public final TableField<UsersRecord, String> LAST_NAME = createField("LAST_NAME", SQLDataType.VARCHAR, this);

	/**
	 * User's encrypted password
	 */
	public final TableField<UsersRecord, String> USER_PASSWORD = createField("USER_PASSWORD", SQLDataType.VARCHAR, this);

	/**
	 * User's email address
	 */
	public final TableField<UsersRecord, String> USER_EMAIL = createField("USER_EMAIL", SQLDataType.VARCHAR, this);

	public Users() {
		super("users", Insieme.INSIEME);
	}

	public Users(String alias) {
		super(alias, Insieme.INSIEME, Users.USERS);
	}

	@Override
	public UniqueKey<UsersRecord> getMainKey() {
		return Keys.KEY_USERS_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public List<UniqueKey<UsersRecord>> getKeys() {
		return Arrays.<UniqueKey<UsersRecord>>asList(Keys.KEY_USERS_PRIMARY, Keys.KEY_USERS_USER_PASSWORD_UNIQUE, Keys.KEY_USERS_USER_EMAIL_UNIQUE);
	}

	@Override
	public com.insieme.common.database.tables.Users as(java.lang.String alias) {
		return new com.insieme.common.database.tables.Users(alias);
	}
}
