/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Insieme extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1414095398;

	/**
	 * The singleton instance of insieme
	 */
	public static final Insieme INSIEME = new Insieme();

	/**
	 * No further instances allowed
	 */
	private Insieme() {
		super("insieme");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(com.insieme.common.database.dto.tables.Users.USERS);
	}
}
