/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

import java.util.Arrays;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import com.insieme.common.database.dto.tables.Users;

/**
 * Insieme schema class for jooq.
 */
public class Insieme extends SchemaImpl {

	private static final long serialVersionUID = -1414095398;

	/**
	 * The singleton instance of insieme
	 */
	public static final Insieme INSIEME = new Insieme();

	/**
	 * No further instances allowed
	 */
	private Insieme() {
		super("insieme");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return Arrays.<Table<?>>asList(Users.USERS);
	}
}
