/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>insieme</code> 
 * schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class Keys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_USER_PASSWORD_UNIQUE = UniqueKeys0.KEY_USERS_USER_PASSWORD_UNIQUE;
	public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_USER_EMAIL_UNIQUE = UniqueKeys0.KEY_USERS_USER_EMAIL_UNIQUE;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings({"hiding", "unchecked"})
	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(com.insieme.common.database.dto.tables.Users.USERS, com.insieme.common.database.dto.tables.Users.USERS.IDUSERS);
		public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_USER_PASSWORD_UNIQUE = createUniqueKey(com.insieme.common.database.dto.tables.Users.USERS, com.insieme.common.database.dto.tables.Users.USERS.USER_PASSWORD);
		public static final org.jooq.UniqueKey<com.insieme.common.database.dto.tables.records.UsersRecord> KEY_USERS_USER_EMAIL_UNIQUE = createUniqueKey(com.insieme.common.database.dto.tables.Users.USERS, com.insieme.common.database.dto.tables.Users.USERS.USER_EMAIL);
	}
}
