/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import com.insieme.common.database.dto.tables.Users;
import com.insieme.common.database.dto.tables.records.UsersRecord;

/**
 * JOOQ insieme keys.
 *
 * A class modelling foreign key relationships between tables of the <code>insieme</code> 
 * schema
 */
public class Keys {

	// IDENTITY definitions

	// UNIQUE and PRIMARY KEY definitions
	public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final UniqueKey<UsersRecord> KEY_USERS_USER_PASSWORD_UNIQUE = UniqueKeys0.KEY_USERS_USER_PASSWORD_UNIQUE;
	public static final UniqueKey<UsersRecord> KEY_USERS_USER_EMAIL_UNIQUE = UniqueKeys0.KEY_USERS_USER_EMAIL_UNIQUE;

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}

	@SuppressWarnings({"unchecked"})
	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, Users.USERS.USER_ID);
		public static final UniqueKey<UsersRecord> KEY_USERS_USER_PASSWORD_UNIQUE = createUniqueKey(Users.USERS, Users.USERS.USER_PASSWORD);
		public static final UniqueKey<UsersRecord> KEY_USERS_USER_EMAIL_UNIQUE = createUniqueKey(Users.USERS, Users.USERS.USER_EMAIL);
	}
}
