/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

import com.insieme.common.database.dto.tables.Users;

/**
 * Insieme JOOQ tables.
 *
 * Convenience access to all tables in insieme
 */
public final class Tables {

	/**
	 * Table to keep track of basic user info.
	 */
	public static final Users USERS = Users.USERS;

	/**
	 * No instances
	 */
	private Tables() {}
}
