/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in insieme
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * Table to keep track of basic user info.
	 */
	public static final com.insieme.common.database.dto.tables.Users USERS = com.insieme.common.database.dto.tables.Users.USERS;

	/**
	 * No instances
	 */
	private Tables() {}
}
