/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * Table to keep track of basic user info.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.4.0"},
                            comments = "This class is generated by jOOQ")
public class UsersRecord extends org.jooq.impl.UpdatableRecordImpl<com.insieme.common.database.dto.tables.records.UsersRecord> {

	private static final long serialVersionUID = 1111160311;

	/**
	 * The table column <code>insieme.users.idUsers</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setIdusers(java.lang.Integer value) {
		setValue(com.insieme.common.database.dto.tables.Users.USERS.IDUSERS, value);
	}

	/**
	 * The table column <code>insieme.users.idUsers</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getIdusers() {
		return getValue(com.insieme.common.database.dto.tables.Users.USERS.IDUSERS);
	}

	/**
	 * User's first name
	 */
	public void setFirstName(java.lang.String value) {
		setValue(com.insieme.common.database.dto.tables.Users.USERS.FIRST_NAME, value);
	}

	/**
	 * User's first name
	 */
	public java.lang.String getFirstName() {
		return getValue(com.insieme.common.database.dto.tables.Users.USERS.FIRST_NAME);
	}

	/**
	 * User's last name
	 */
	public void setLastName(java.lang.String value) {
		setValue(com.insieme.common.database.dto.tables.Users.USERS.LAST_NAME, value);
	}

	/**
	 * User's last name
	 */
	public java.lang.String getLastName() {
		return getValue(com.insieme.common.database.dto.tables.Users.USERS.LAST_NAME);
	}

	/**
	 * User's encrypted password
	 */
	public void setUserPassword(java.lang.String value) {
		setValue(com.insieme.common.database.dto.tables.Users.USERS.USER_PASSWORD, value);
	}

	/**
	 * User's encrypted password
	 */
	public java.lang.String getUserPassword() {
		return getValue(com.insieme.common.database.dto.tables.Users.USERS.USER_PASSWORD);
	}

	/**
	 * User's email address
	 */
	public void setUserEmail(java.lang.String value) {
		setValue(com.insieme.common.database.dto.tables.Users.USERS.USER_EMAIL, value);
	}

	/**
	 * User's email address
	 */
	public java.lang.String getUserEmail() {
		return getValue(com.insieme.common.database.dto.tables.Users.USERS.USER_EMAIL);
	}

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(com.insieme.common.database.dto.tables.Users.USERS);
	}
}
