/**
 * This class is generated by jOOQ
 */
package com.insieme.common.database.dto.tables.records;

import org.jooq.impl.UpdatableRecordImpl;

import com.insieme.common.database.dto.tables.Users;

/**
 * This class is generated by jOOQ.
 *
 * Table to keep track of basic user info.
 */
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

	private static final long serialVersionUID = 1111160311;

	/**
	 * The table column <code>insieme.users.idUsers</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setIdusers(java.lang.String value) {
		setValue(Users.USERS.USER_ID, value);
	}

	/**
	 * The table column <code>insieme.users.idUsers</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.String getIdusers() {
		return getValue(Users.USERS.USER_ID);
	}

	/**
	 * User's first name
	 */
	public void setFirstName(java.lang.String value) {
		setValue(Users.USERS.FIRST_NAME, value);
	}

	/**
	 * User's first name
	 */
	public java.lang.String getFirstName() {
		return getValue(Users.USERS.FIRST_NAME);
	}

	/**
	 * User's last name
	 */
	public void setLastName(java.lang.String value) {
		setValue(Users.USERS.LAST_NAME, value);
	}

	/**
	 * User's last name
	 */
	public java.lang.String getLastName() {
		return getValue(Users.USERS.LAST_NAME);
	}

	/**
	 * User's encrypted password
	 */
	public void setUserPassword(java.lang.String value) {
		setValue(Users.USERS.USER_PASSWORD, value);
	}

	/**
	 * User's encrypted password
	 */
	public java.lang.String getUserPassword() {
		return getValue(Users.USERS.USER_PASSWORD);
	}

	/**
	 * User's email address
	 */
	public void setUserEmail(java.lang.String value) {
		setValue(Users.USERS.USER_EMAIL, value);
	}

	/**
	 * User's email address
	 */
	public java.lang.String getUserEmail() {
		return getValue(Users.USERS.USER_EMAIL);
	}

	/**
	 * Create a detached UsersRecord
	 */
	public UsersRecord() {
		super(Users.USERS);
	}
}
